# Generated by Django 3.2.7 on 2021-09-17 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0002_auto_20210911_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='plans',
            field=models.CharField(choices=[('Diamond', 'Diamond'), ('Gold', 'Gold'), ('Silver', 'Silver')], default='PLANS[0]', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default='/Koala.jpg/', upload_to=''),
        ),
        migrations.CreateModel(
            name='customer_container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.IntegerField(null=True)),
                ('container', models.OneToOneField(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.container')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
