# Generated by Django 3.2.7 on 2021-09-17 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_alter_customer_container_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_container',
            name='container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.container'),
        ),
    ]
