# Generated by Django 3.2.7 on 2021-09-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_alter_customer_container_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='url_link',
            field=models.CharField(max_length=350, null=True),
        ),
    ]
