# Generated by Django 3.2.7 on 2021-09-23 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_customer_url_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='container_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('container', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.customer_container')),
            ],
        ),
    ]
