# Generated by Django 3.2.7 on 2021-09-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_container_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='container_item',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='container_item',
            name='tracking_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
