# Generated by Django 3.2.7 on 2021-10-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_alter_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default='css/images/Koala11.bmp/', null=True, upload_to=''),
        ),
    ]
