# Generated by Django 3.2.7 on 2021-10-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0019_alter_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/propic.jpeg/', null=True, upload_to=''),
        ),
    ]
