# Generated by Django 3.2.7 on 2021-10-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0020_alter_customer_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_container',
            name='latitude',
            field=models.IntegerField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customer_container',
            name='longitude',
            field=models.IntegerField(max_length=6, null=True),
        ),
    ]
