# Generated by Django 3.2.7 on 2021-10-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0021_auto_20211008_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='container_item',
            name='latitude',
            field=models.IntegerField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='container_item',
            name='longitude',
            field=models.IntegerField(max_length=6, null=True),
        ),
    ]
