# Generated by Django 3.2.7 on 2021-10-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0022_auto_20211008_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container_item',
            name='latitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='container_item',
            name='longitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer_container',
            name='latitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer_container',
            name='longitude',
            field=models.IntegerField(null=True),
        ),
    ]
