# Generated by Django 3.2.7 on 2021-10-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0023_auto_20211010_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container_item',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
